/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import grafos.AlgoritmosGrafos;
import grafos.BuscaEmLargura;
import grafos.Djikstra;
import grafos.Grafo;
import grafos.TipoDeRepresentacao;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tribi
 */
public class djikstra extends javax.swing.JFrame {

    /**
     * Creates new form BuscaLargura
     */
    boolean carregado = false;
    AlgoritmosGrafos a;
    Grafo g;
    Djikstra b;

    public djikstra(String path, TipoDeRepresentacao t) throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);

        a = new AlgoritmosGrafos();
        g = a.carregarGrafo(path, t);
        carregado = true;

        setNumVertices(Integer.toString(g.numeroDeVertices()));
        setNumArestas(Integer.toString(g.numeroDeArestas()));

    }

    public void setNumVertices(String n) {
        jLabelNumVertices.setText(n);
    }

    public void setNumArestas(String n) {
        jLabelNumArestas.setText(n);
    }

    public void populaBFS() {
        DefaultTableModel table = (DefaultTableModel) jTableBFS.getModel();
        int pai, distancia;
        boolean acessivel;
        for (int i = 0; i < g.numeroDeVertices(); i++) {
            pai = b.pai[i];
            distancia = (int) b.d[i];
            //acessivel = b.acessivel(i);
            table.addRow(new Integer[]{i, pai, distancia});

        }
    }
    public void populaBFSunica(int vertice) {
        DefaultTableModel table = (DefaultTableModel) jTableBFSunico.getModel();
        int pai, distancia;
       
       
            pai = b.pai[vertice];
            distancia =(int) b.d[vertice];
            
            table.addRow(new Integer[]{ pai, distancia});

        
    }

    public void limpaTabela() {
        DefaultTableModel table = (DefaultTableModel) jTableBFS.getModel();
        while (table.getRowCount() > 0) {
            table.removeRow(0);
        }
    }
    
    public void limpaTable() {
        DefaultTableModel table = (DefaultTableModel) jTableBFSunico.getModel();
        while (table.getRowCount() > 0) {
            table.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBFS = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNumVertices = new javax.swing.JLabel();
        jLabelNumArestas = new javax.swing.JLabel();
        jBtnVai = new javax.swing.JButton();
        jTextVerticeInicial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBFSunico = new javax.swing.JTable();
        jTextVertice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelVerticeInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableBFS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Vértice", "Pai", "Distancia Raiz"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableBFS);
        if (jTableBFS.getColumnModel().getColumnCount() > 0) {
            jTableBFS.getColumnModel().getColumn(0).setResizable(false);
            jTableBFS.getColumnModel().getColumn(1).setResizable(false);
            jTableBFS.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Número de Vértices");

        jLabel2.setText("Número de Arestas");

        jLabel3.setText("Raiz - Vértice:");

        jBtnVai.setText("Vai!");
        jBtnVai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVaiActionPerformed(evt);
            }
        });

        jLabel4.setText("Vértice inicial:");

        jTableBFSunico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pai", "Distancia à origem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableBFSunico);
        if (jTableBFSunico.getColumnModel().getColumnCount() > 0) {
            jTableBFSunico.getColumnModel().getColumn(0).setResizable(false);
            jTableBFSunico.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNumVertices))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNumArestas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelVerticeInicial))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextVerticeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnVai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jTextVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNumVertices))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNumArestas))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelVerticeInicial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextVerticeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnVai))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextVertice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVaiActionPerformed
        // TODO add your handling code here:
        boolean pronto = true;
        if (!carregado) {
            JOptionPane.showMessageDialog(null, "Grafo em carregamento...");
            pronto = false;
        }
        if ("".equals(jTextVerticeInicial.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione um vértice inicial");
            pronto = false;

        }
        int v = Integer.parseInt(jTextVerticeInicial.getText());
        if (v < 0 || v > g.numeroDeVertices()) {
            JOptionPane.showMessageDialog(null, "Selecione um vértice válido");
            pronto = false;
        }

        if (pronto) {
            try {
                b = new grafos.Djikstra(g, v);
                b.runDjikstra();
                limpaTabela();
                populaBFS();
                jLabelVerticeInicial.setText(jTextVerticeInicial.getText());
            } catch (Exception ex) {
                Logger.getLogger(djikstra.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jBtnVaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int vertice = Integer.parseInt(jTextVertice.getText());
        limpaTable();
        populaBFSunica(vertice);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(djikstra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(djikstra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(djikstra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(djikstra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnVai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNumArestas;
    private javax.swing.JLabel jLabelNumVertices;
    private javax.swing.JLabel jLabelVerticeInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBFS;
    private javax.swing.JTable jTableBFSunico;
    private javax.swing.JTextField jTextVertice;
    private javax.swing.JTextField jTextVerticeInicial;
    // End of variables declaration//GEN-END:variables
}
